# Generated by Django 5.1.6 on 2025-02-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='topic',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estimates.task'),
            preserve_default=False,
        ),
    ]
