# Generated by Django 5.1.6 on 2025-02-26 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_rename_identifies_room_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='public_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
