# Generated by Django 5.1.6 on 2025-03-11 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_alter_room_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_external_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
