# Generated by Django 5.1.6 on 2025-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_room_finished_task_completed_vote_voter_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_external_id',
            field=models.UUIDField(),
        ),
    ]
