# Generated by Django 5.1.6 on 2025-03-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_alter_vote_voter_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='finished',
        ),
    ]
